# Generated by Django 2.0.5 on 2018-05-21 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20180520_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='repair_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='维修日期'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='request_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报修人员'),
        ),
    ]
