# Generated by Django 2.0.5 on 2018-05-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20180521_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='contact_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='联系方式'),
        ),
    ]
