# Generated by Django 2.0.5 on 2018-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20180521_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrecord',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='消费金额'),
        ),
    ]
