# Generated by Django 2.0.5 on 2018-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_consumptionrecord_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
