# Generated by Django 2.0.5 on 2018-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20180521_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(default=1, max_length=32, verbose_name='联系方式'),
        ),
    ]
