# Generated by Django 2.0.5 on 2018-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_guestsource_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='url_name',
            field=models.CharField(max_length=64),
        ),
    ]
