# Generated by Django 2.0.5 on 2018-06-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20180607_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='VIP',
        ),
    ]
