# Generated by Django 2.0.5 on 2018-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_customer_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='VIP',
            field=models.SmallIntegerField(choices=[(1, 'REG'), (2, 'VIP'), (3, 'SVIP')], default=1, verbose_name='会员'),
        ),
    ]
